// react搭建/src/App.jsx
import React, { memo, useState } from 'react'
import './style.less'

const App = memo(() => {
  const message = 'react'
  const [count, setCount] = useState(0)

  return (
    <div>
      <h1>Hello {message}</h1>
      <h2>Count: {count}</h2>
      <button onClick={() => setCount(count + 1)}>+1</button>
      <button onClick={() => setCount(count - 1)}>+1</button>
    </div>
  )
})

export default App

// vue搭建/src/App.vue
<template>
  <div class="app">
    <h1>Hello {{ message }}</h1>
    <h2>{{ count }}</h2>
    <button @click="handleAdd">+11</button>
    <button @click="handleDes">-1</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const count = ref<number>(0)
const message = 'vue'

const handleAdd = () => count.value++
const handleDes = () => count.value--
</script>

<style scoped lang="less">
.app {
  background-color: yellow;
  h1 {
    color: red;
  }
}
</style>
